-- SEED nội bộ mở rộng (tự sinh từ data.js + nhanvien.html + bangtin.html)

-- Toà nhà + phòng (JSON blob)
INSERT INTO toa_nha (bid,grp,data) VALUES ('b1','ptro','{"bid":"b1","addr":"Huỳnh Khương An, P.8","addrFull":"60/18A Huỳnh Khương An, Phường 8, Quận Gò Vấp, TP. Hồ Chí Minh","quan":"Gò Vấp","nv":"Nguyễn Hữu Thắng","chuNhaSdt":"0909 111 222","zaloNhom":"https://zalo.me/g/example1","tiktokUrl":"7380000000000000001","date":"Hôm nay","imgs":["#a8c4f0,#6b9fdf","#98bae0,#6090d0","#88aed8,#5080c0"],"tienich":["Camera 24/7","Bảo vệ","Wifi","Chỗ để xe"],"rooms":[{"rid":"b1r1","loai":"Ký túc xá","tags":["Cửa sổ"],"noithat":["Giường","Tủ quần áo"],"m2":"~18","price":"1,4TR","coc":"1 tháng","cocsố":"1.400.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"ktx","note":"Bao gồm tất cả chi phí"},"soLuong":8,"soTrong":3,"status":"open"},{"rid":"b1r2","loai":"Ký túc xá","tags":["Duplex","Gác lửng"],"noithat":["Giường","Tủ quần áo","Bàn ghế"],"m2":"~22","price":"1,8TR","coc":"1 tháng","cocsố":"1.800.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"ktx","note":"Bao gồm tất cả chi phí"},"soLuong":4,"soTrong":0,"status":"block"}]}');
INSERT INTO toa_nha (bid,grp,data) VALUES ('b2','ptro','{"bid":"b2","addr":"Nguyễn Oanh, P.17","addrFull":"45 Nguyễn Oanh, Phường 17, Quận Gò Vấp, TP. Hồ Chí Minh","quan":"Gò Vấp","nv":"Nguyễn Hữu Thắng","chuNhaSdt":"0918 222 333","zaloNhom":"https://zalo.me/g/example2","tiktokUrl":"","date":"Hôm qua","imgs":["#b0cef5,#7aaee5","#a0bef0,#6a9ee0"],"tienich":["Thang máy","Wifi","Máy giặt","Chỗ để xe"],"rooms":[{"rid":"b2r1","loai":"Phòng trọ","tags":["Cửa sổ"],"noithat":["Máy lạnh","Bàn ghế"],"m2":"20","price":"2,8TR","coc":"1 tháng","cocsố":"2.800.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"tro","dien":"4.000đ/kWh","nuoc":"100.000đ/người","xe":"150.000đ/xe","dv":"100.000đ/phòng"},"soLuong":6,"soTrong":2,"status":"open"},{"rid":"b2r2","loai":"Phòng trọ","tags":["Ban công","1PN"],"noithat":["Máy lạnh","Máy nước nóng","Bàn ghế"],"m2":"25","price":"3,5TR","coc":"1 tháng","cocsố":"3.500.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"tro","dien":"4.000đ/kWh","nuoc":"100.000đ/người","xe":"150.000đ/xe","dv":"100.000đ/phòng"},"soLuong":4,"soTrong":1,"status":"wait"}]}');
INSERT INTO toa_nha (bid,grp,data) VALUES ('b3','ptro','{"bid":"b3","addr":"Đinh Tiên Hoàng, P.3","addrFull":"128 Đinh Tiên Hoàng, Phường 3, Quận Bình Thạnh, TP. Hồ Chí Minh","quan":"Bình Thạnh","nv":"Trần Thị Mai","chuNhaSdt":"0933 444 555","zaloNhom":"","tiktokUrl":"7380000000000000002","date":"01/07","imgs":["#c0d8f8,#90b8e8","#b0c8f0,#80a8e0"],"tienich":["Camera 24/7","Thang máy","Điều hòa","Wifi"],"rooms":[{"rid":"b3r1","loai":"Căn hộ DV","tags":["Studio","Ban công"],"noithat":["Máy lạnh","Tủ lạnh","Máy nước nóng","Bàn ghế","Giường"],"m2":"35","price":"5,2TR","coc":"1 tháng","cocsố":"5.200.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"tro","dien":"4.000đ/kWh","nuoc":"100.000đ/người","xe":"150.000đ/xe","dv":"100.000đ/phòng"},"soLuong":1,"soTrong":1,"status":"open"}]}');
INSERT INTO toa_nha (bid,grp,data) VALUES ('b4','ptro','{"bid":"b4","addr":"Cách Mạng Tháng 8, P.10","addrFull":"310 Cách Mạng Tháng 8, Phường 10, Quận 10, TP. Hồ Chí Minh","quan":"Quận 10","nv":"Lê Minh Hùng","chuNhaSdt":"0944 888 999","zaloNhom":"https://zalo.me/g/example5","tiktokUrl":"7380000000000000003","date":"28/06","imgs":["#a0c0f2,#70a0e2","#90b0e8,#6090d8"],"tienich":["Camera 24/7","Thang máy","Bảo vệ","Wifi"],"rooms":[{"rid":"b4r1","loai":"Ký túc xá","tags":["Cửa sổ"],"noithat":["Giường","Tủ quần áo","Bàn ghế"],"m2":"~15","price":"1,2TR","coc":"1 tháng","cocsố":"1.200.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"ktx","note":"Bao gồm tất cả chi phí"},"soLuong":12,"soTrong":5,"status":"open"},{"rid":"b4r2","loai":"Phòng trọ","tags":["Ban công"],"noithat":["Máy lạnh","Giường","Bàn ghế"],"m2":"22","price":"3,2TR","coc":"1 tháng","cocsố":"3.200.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"tro","dien":"4.000đ/kWh","nuoc":"100.000đ/người","xe":"150.000đ/xe","dv":"100.000đ/phòng"},"soLuong":3,"soTrong":0,"status":"block"}]}');
INSERT INTO toa_nha (bid,grp,data) VALUES ('cc_b1','cc','{"bid":"cc_b1","addr":"Hoàng Diệu, P.Tân Phú","addrFull":"18 Hoàng Diệu, Phường Tân Phú, Quận Phú Nhuận, TP. Hồ Chí Minh","quan":"Phú Nhuận","nv":"Phạm Thị Lan","chuNhaSdt":"0933 456 333","zaloNhom":"","tiktokUrl":"7380000000000000010","date":"01/07","imgs":["#c8d8f8,#8ab0e8","#b8caf5,#7aa0e2","#a8baf0,#6a90da"],"tienich":["Camera 24/7","Wifi","Chỗ để xe ô tô"],"rooms":[{"rid":"cc_b1r1","loai":"Nhà nguyên căn","tags":["3PN","Ban công"],"noithat":["Bếp","Máy lạnh"],"m2":"80","price":"8TR","coc":"2 tháng","cocsố":"16.000.000đ","hh":"60%–80%","hd":"6T–12T","chiPhi":{"loai":"nha","note":"Điện nước theo đơn giá nhà nước"},"soLuong":1,"soTrong":1,"status":"open"}]}');
INSERT INTO toa_nha (bid,grp,data) VALUES ('cc_b2','cc','{"bid":"cc_b2","addr":"Masteri Thảo Điền, P.Thảo Điền","addrFull":"159 Xa Lộ Hà Nội, Phường Thảo Điền, TP. Thủ Đức, TP. Hồ Chí Minh","quan":"Thủ Đức","nv":"Phạm Thị Lan","chuNhaSdt":"0955 123 456","zaloNhom":"https://zalo.me/g/masteri","tiktokUrl":"7380000000000000011","date":"29/06","imgs":["#b8d0f5,#7aa8e5","#a8c0ec,#6a98dc","#98b0e4,#5888cc"],"tienich":["Hồ bơi","Gym","Thang máy","Bảo vệ 24/7","Chỗ để xe ô tô"],"rooms":[{"rid":"cc_b2r1","loai":"Chung cư","tags":["2PN","Ban công"],"noithat":["Đầy đủ nội thất","Máy lạnh","Tủ lạnh"],"m2":"65","price":"12TR","coc":"2 tháng","cocsố":"24.000.000đ","hh":"50%–80%","hd":"6T–12T","chiPhi":{"loai":"cc","note":"Điện nước theo đơn giá nhà nước","xe":"150.000đ/xe","ql":"45.000đ/m²"},"soLuong":3,"soTrong":2,"status":"wait"},{"rid":"cc_b2r2","loai":"Chung cư","tags":["3PN","Penthouse"],"noithat":["Đầy đủ nội thất","Máy lạnh","Tủ lạnh","Bếp"],"m2":"95","price":"22TR","coc":"2 tháng","cocsố":"44.000.000đ","hh":"60%–80%","hd":"12T–24T","chiPhi":{"loai":"cc","note":"Điện nước theo đơn giá nhà nước","xe":"200.000đ/xe","ql":"45.000đ/m²"},"soLuong":1,"soTrong":0,"status":"block"}]}');
INSERT INTO toa_nha (bid,grp,data) VALUES ('cc_b3','cc','{"bid":"cc_b3","addr":"Nguyễn Thị Minh Khai, P.5","addrFull":"102 Nguyễn Thị Minh Khai, Phường 5, Quận 3, TP. Hồ Chí Minh","quan":"Quận 3","nv":"Lê Minh Hùng","chuNhaSdt":"0911 789 012","zaloNhom":"https://zalo.me/g/q3building","tiktokUrl":"","date":"25/06","imgs":["#d0c8f8,#9890e8","#c0b8f0,#8880d8"],"tienich":["Thang máy","Camera 24/7","Bảo vệ"],"rooms":[{"rid":"cc_b3r1","loai":"Nhà nguyên căn","tags":["4PN","Ban công"],"noithat":["Bếp","Bàn ghế"],"m2":"120","price":"18TR","coc":"2 tháng","cocsố":"36.000.000đ","hh":"60%–80%","hd":"12T–24T","chiPhi":{"loai":"nha","note":"Điện nước theo đơn giá nhà nước"},"soLuong":1,"soTrong":1,"status":"open"}]}');

-- Nhân viên
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('MT','Minh Trọ','minhtro@hthome.vn','Sale cấp 2','Gò Vấp',12,'48tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('TH','Thu Hà','thuha@hthome.vn','Sale cấp 1','Gò Vấp',18,'38tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('QB','Quốc Bảo','quocbao@hthome.vn','Sale cấp 2','Bình Thạnh',10,'27tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('LA','Lan Anh','lananh@hthome.vn','Sale cấp 2','Phú Nhuận',7,'20tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('ĐH','Đức Huy','duchuy@hthome.vn','Sale cấp 2','Tân Bình',5,'13tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('NT','Ngọc Trâm','ngoctram@hthome.vn','Sale cấp 2','Gò Vấp',9,'24tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('VK','Văn Khoa','vankhoa@hthome.vn','Sale cấp 2','Quận 12',6,'16tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('PT','Phương Thảo','phuongthao@hthome.vn','Sale cấp 2','Bình Thạnh',8,'21tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('HT','Hữu Thắng','huuthang@hthome.vn','Sale cấp 2','Thủ Đức',4,'11tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('TN','Tuyết Nhi','tuyetnhi@hthome.vn','Sale cấp 1','Phú Nhuận',14,'31tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('GP','Gia Phú','giaphu@hthome.vn','Sale cấp 1','Tân Bình',11,'26tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('KL','Khánh Linh','khanhlinh@hthome.vn','Sale cấp 1','Quận 12',9,'22tr','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('ĐA','Quản Đức Anh','ducanh@hthome.vn','Manager','Toàn khu',0,'—','Active');
INSERT INTO nhan_vien (av,name,email,role,kv,deal,hh,st) VALUES ('ĐB','Trần Đình Bảo','dinhbao@hthome.vn','Admin','Toàn hệ thống',0,'—','Đã nghỉ');

-- Bảng tin
INSERT INTO bang_tin (av,author,role,time,pinned,tag_cls,tag_txt,title,body,likes,cmt) VALUES ('QĐ','Quản Đức Anh','Manager','2 giờ trước',1,'tag--report','📊 Báo cáo tháng','KPI tháng 7: HT HOME đạt 105% target','Chúc mừng cả team! Doanh thu tháng 7 đạt 487tr (target 465tr), vượt 105% kế hoạch. Đóng góp lớn nhất từ khu Gò Vấp và Bình Thạnh. Chi tiết báo cáo đã gửi qua email, mọi người xem và chuẩn bị cho mục tiêu tháng 8 nhé.',14,5);
INSERT INTO bang_tin (av,author,role,time,pinned,tag_cls,tag_txt,title,body,likes,cmt) VALUES ('TB','Trần Đình Bảo','Admin','5 giờ trước',0,'tag--congrat','🎉 Chúc mừng','Chị Thu Hà lên Sale cấp 1','Xin chúc mừng chị Thu Hà chính thức thăng cấp Sale cấp 1 với 18 deal chốt trong tháng 7! Một cột mốc xứng đáng cho sự nỗ lực bền bỉ. Cả nhà cùng vào chúc mừng chị nào 👏',22,11);
INSERT INTO bang_tin (av,author,role,time,pinned,tag_cls,tag_txt,title,body,likes,cmt) VALUES ('TB','Trần Đình Bảo','Admin','Hôm qua',0,'tag--system','🔧 Cập nhật hệ thống','Cập nhật quy trình upload HĐ','Từ 15/07, tất cả deal cần upload đủ 3 trang HĐ (trang thông tin, trang điều khoản, trang ký) trước khi chuyển sang trạng thái "Đã chốt". Deal thiếu ảnh sẽ không được tính hoa hồng. Mọi người lưu ý cập nhật các deal đang mở.',9,3);
INSERT INTO bang_tin (av,author,role,time,pinned,tag_cls,tag_txt,title,body,likes,cmt) VALUES ('QĐ','Quản Đức Anh','Manager','2 ngày trước',0,'tag--meeting','📅 Meeting','Họp tổng kết tháng','Lịch họp tổng kết tháng 7 & triển khai mục tiêu tháng 8: 9h00 thứ Hai (05/08) tại phòng họp tầng 3. Nội dung: review KPI từng khu, phân bổ quỹ phòng mới, chốt chính sách hoa hồng Q3. Đề nghị cả team có mặt đầy đủ và đúng giờ.',7,4);
